### ISSUE TITLE
Milestone 4.0

### ISSUE THREAD

**Issue by lepture** [avelino/liquidluck#101]
Things we should do in 4.0:
1. [ ] replace the current command line with [terminal](https://lepture.com/lepture/terminal), the command line should be pretty.
2. [ ] make the code more friendly to developers, that means it can be invoked be other program
3. [ ] improve compatibility, (Python 2.6+ and Python 3.3+)
4. [ ] rewrite the documentation

This may take a long time, since I am busy with other things.
